<?php

/**
 * Author:Evan Minor
 * Date: 3/8/2022
 * File: basepluscommissionemployee.class.php
 * Description: This class will take the commission of an employee and add the base salary
 * Base_Salary + Commission
 * *The commission was calculated in the ComissionEmployee Class
 */
class BasePlusCommissionEmployee extends commissionemployee
{
    //private data members
    private $base_salary;

    //constructor

    public function __construct($bs){
        $this->base_salary = $bs;
    }

    public function getBaseSalary(){
        return $this->base_salary;
    }

    public function getPaymentAmount()
    {
        return parent::getPaymentAmount(); // TODO: Change the autogenerated stub
    }

    public function toString()
    {
        return "$this->base_salary";
    }
}


